#!/usr/bin/env bash

find_expression=( find . -name '*_shpec.*' )
shpec_files=( $("${find_expression[@]}" -print) )

printf 'shpec %s\n' "${shpec_files[*]}"

"${find_expression[@]}" -print0 | xargs -0I filename bash -c 'shpec filename'
