#!/usr/bin/env bash

source stdlib

exit_if_package_is_installed () {
  ! package_is_installed "${1}" || exit 0
}

install_local_package () {
  sudo dpkg -i "${1}"
}

install_package () {
  local package

  package="${1}"
  ! package_is_installed "${package}" || return 0
  update_apt
  sudo apt-get install "${package}"
}

package_is_installed () {
  dpkg --get-selections "${1}" 2>/dev/null | grep -q "^${1}\\(:amd64\\)\\?[[:space:]]\\+install\$" >/dev/null
}

reinstall_package () {
  local package

  package="${1}"
  uninstall_package "${package}"
  install_package "${package}"
}

uninstall_package () {
  local package

  package="${1}"
  package_is_installed "${package}" || return 0
  sudo apt-get purge "${package}"
}

update_apt () {
  local apt_date
  local now_date
  local last_update
  local update_interval

  apt_date="$(stat -c %Y '/var/cache/apt/pkgcache.bin')"
  now_date="$(date +'%s')"
  last_update="$((${now_date} - ${apt_date}))"
  update_interval="$((24 * 60 * 60))"
  [[ "${last_update}" -lt "${update_interval}" ]] || sudo apt-get update -qq
}
