#!/usr/bin/env bash

# https://stackoverflow.com/questions/3685970/check-if-an-array-contains-a-value#answer-8574392
array_contains () {
  local elem
  for elem in "${@:2}"; do
    if [[ "${elem}" == "${1}" ]]; then
      return 0
    fi
  done
  return 1
}

array_find () {
  local i
  local item
  local array

  item="${1}"
  shift
  array=( "${@}" )
  for i in "${!array[@]}"; do
    if [[ "${array[${i}]}" == "${item}" ]]; then
      echo "${i}"
      return 0
    fi
  done
  return 1
}
