#!/usr/bin/env bash

# https://stackoverflow.com/questions/3685970/check-if-an-array-contains-a-value#answer-8574392
array_contains () {
  local elem
  for elem in "${@:2}"; do
    [[ "${elem}" == "${1}" ]] && return 0
  done
  return 1
}
