#!/usr/bin/env bash

# https://stackoverflow.com/questions/1527049/bash-join-elements-of-an-array#answer-17841619
str_join () {
  local delim

  delim="${1}"
  shift
  echo -n "${1}"
  shift
  printf "%s" "${@/#/${delim}}"
}

str_split () {
  local delim
  local target

  delim="${1}"
  target="${2}"
  echo $( set -- "${target}"; IFS="${delim}"; declare -a array=( ${*} ); echo "${array[@]}" )
}
