#!/usr/bin/env bash

# https://stackoverflow.com/questions/1527049/bash-join-elements-of-an-array#answer-17841619
join_str () {
  local d="${1}"
  shift
  echo -n "${1}"
  shift
  printf "%s" "${@/#/$d}"
}
